# Generated by Django 3.0.1 on 2021-02-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateExam',
            fields=[
                ('eid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('exam_name', models.CharField(max_length=50)),
                ('subject', models.TextField(max_length=50)),
                ('duration', models.IntegerField()),
                ('tmarks', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('eid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('all_emails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SetQPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.CharField(max_length=20)),
                ('questions', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('corr_ans', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
