# Generated by Django 3.0.1 on 2021-02-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SetQPaper',
        ),
    ]
