# Generated by Django 3.0.1 on 2021-02-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_delete_setqpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetQPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eid', models.CharField(max_length=20)),
                ('questions', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('corr_ans', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
