# Generated by Django 3.1.2 on 2021-03-24 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_delete_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profiles/profile.png', upload_to='profiles/')),
                ('username', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default=None, max_length=32)),
                ('address', models.CharField(default=None, max_length=99)),
                ('city', models.CharField(default=None, max_length=20)),
                ('phone', models.CharField(default=None, max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='phone')),
                ('state', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
