# Generated by Django 3.1.2 on 2021-03-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_register_userprof'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
